// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqersrfjnlijsyipdxqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZXJzcmZqbmxpanN5aXBkeHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDQyMjMsImV4cCI6MjA1OTcyMDIyM30.EfU861sdMHJnzT88zM4eUxMqGIfSpbeKX10au8Zqh-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);